# Workflow for building and validating Next.js site
#
name: Build Next.js Site

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main", "develop"]
    paths:
      - 'apps/web/**'
      - 'package.json'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build with Next.js
        run: npm run build:web

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: ./apps/web/.next
          retention-days: 5
